config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root                     'static_pages#home'
  get    '/help',      to: 'static_pages#help'
  get    '/repairs',   to: 'static_pages#repairs'
  get    '/customers', to: 'static_pages#customers'
  get    '/about',     to: 'static_pages#about'
  get    '/contact',   to: 'static_pages#contact'

  get    '/signup',    to: 'users#new'
  post   '/signup',    to: 'users#create'

  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  resources :users
  resources :orders, only: [:create, :destroy, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, inverse_of: :orders
  has_many :tag_assignments, foreign_key: 'tagged_order_id'
  has_many :tags, through: :tag_assignments
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :description, presence: true, length: {maximum: 300}
  validate :picture_size


  def tag(tag)
    tags << tag
  end

  def untag(tag)
    tags.delete(tag)
  end

  def tagged_with?(tag)
    tags.include?(tag)
  end


  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, 'should be less than 5MB')
      end
    end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, 'error') %>.
      </div>
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="orders">
      <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_order_form.html.erb
<%= form_for(@order, html: {multipart: true}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :description, placeholder: 'Describe new order…' %>
    </div>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    <section class="tag_list">
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |cb| %>
          <% cb.label { cb.check_box + cb.text } %>
      <% end %>
    </section>
<% end %>

<script type="text/javascript">
    $('#order_picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/shared/_tag_form.html.erb
<%= form_for @order do |f| %>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |cb| %>
        <% cb.label { cb.check_box + cb.text } %>
    <% end %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to 'view my profile', current_user %></span>
<span><%= pluralize(current_user.orders.count, 'order') %></span>